apiVersion: v1
kind: Service
metadata:
  name: user-app-svc
  namespace: user-app
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort